Vagrant.configure("2") do |config|
  config.vm.box = "vagrant_local"
  config.vm.hostname = "testserver"
  config.vm.box_url = "file:/Users/xujianhui/figospace/dev_ops/boxes/ubuntu_trusty64.box"
  config.vm.network "private_network", ip:"10.10.10.10"
  config.vm.provision "shell", inline: "sudo apt-get update; sudo ln -sf /usr/bin/python3 /usr/bin/python"
  config.vm.provision "ansible" do |ans| 
    ans.playbook = "vagrant_playbook.yml" 
    ans.inventory_path = "/Users/xujianhui/figospace/dev_ops/devops_work/vagrant/ansible/local/inventory.yml"
  end


  config.vm.provider   "virtualbox" do |virtualbox|
    virtualbox.name = "ch03"
  end
end
