
Vagrant.configure("2") do |config|

    config.vm.define "ch01" do |vb|
        config.vm.provider "virtualbox" do |v|
          v.memory = 512
          v.cpus = 1
        end
        vb.vm.box_url = "file:/Users/xujianhui/figospace/dev_ops/boxes/CentOS-7-x86_64-Vagrant-1905_01.VirtualBox.box"
        vb.vm.host_name = "ch01"
        vb.vm.network :private_network, ip: "10.10.10.20"
        vb.vm.box = "my-centos7"
    end

    config.vm.define "ch02" do |vb|
        config.vm.provider "virtualbox" do |v|
            v.memory = 512
            v.cpus = 1
        end
        vb.vm.box_url = "file:/Users/xujianhui/figospace/dev_ops/boxes/CentOS-7-x86_64-Vagrant-1905_01.VirtualBox.box"
        vb.vm.host_name = "ch02"
        vb.vm.network :private_network, ip: "10.10.10.21"
        vb.vm.box = "my-centos7"
    end

    config.vm.define "ch03" do |vb|
        config.vm.provider "virtualbox" do |v|
            v.memory = 512
            v.cpus = 1
        end
        vb.vm.box_url = "file:/Users/xujianhui/figospace/dev_ops/boxes/CentOS-7-x86_64-Vagrant-1905_01.VirtualBox.box"
        vb.vm.host_name = "ch03"
        vb.vm.network :private_network, ip: "10.10.10.22"
        vb.vm.box = "my-centos7"
    end

end