ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure("2") do |config|
  config.vm.define "default",primary: true do |master|
    config.vm.network "private_network",  ip:"10.10.10.111"
    #config.vm.network "forwarded_port", id: "ssh", host: 2222, guest: 22
    #config.vm.network "forwarded_port", id: "nginx", host: 8080, guest: 80
  end

  config.vm.provider "docker" do |d|
  #d.image = "bashtoni/centos7-vagrant"
  #d.ports = ["80:3000"]
  d.build_dir = "."
  d.has_ssh=true
  d.remains_running = true
  end
 config.ssh.username = "vagrant"
 config.ssh.private_key_path = "/Users/xujianhui/mobvista/mtg/github/devops_work/vagrant_docker/hello/key/vagrant"
 config.vm.synced_folder ".", "/vagrant"
end
